const fifity_smart_collections = [
  {
    id: 275590742212,
    handle: "ingredients-acidulants-and-preservatives",
    title: "Acidulants, Preservatives and Shelflife Extenders",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      "Shelf life is critical to any food product. There are several techniques to improve shelf life, from controlling the pH using acid buffers, to chemical preservatives. But shelflife goes beyond spoilage, consumers today expect the products they eat to taste just as good on the day they eat it as it was when the product was made. Thus crumbling, separation and other such issues also need to be addressed.",
    published_at: "2021-08-30T09:55:35+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Acidulant",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Preservatives",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Shelf life extender",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/275590742212",
  },
  {
    id: 276778057924,
    handle: "all",
    title: "All",
    updated_at: "2022-11-22T13:12:18+05:30",
    body_html: "",
    published_at: "2021-09-14T09:13:09+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "variant_price",
        relation: "greater_than",
        condition: "0",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/276778057924",
  },
  {
    id: 271731523780,
    handle: "company-ambrosia-nuts",
    title: "Ambrosia Nuts",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html: "",
    published_at: "2021-07-17T15:24:35+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "AMBROSIA",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/271731523780",
  },
  {
    id: 261639110852,
    handle: "ingredients-cake-premix",
    title: "Bake the best with Cake Premix",
    updated_at: "2022-11-08T10:51:31+05:30",
    body_html:
      '<h2 dir="auto" data-pm-slice="1 1 []">The one-stop destination for high-quality cake premix </h2>\n<h3 dir="auto">Why Use A Premix?</h3>\n<p>There are several reasons to use a premix, here are the top 4</p>\n<h3 dir="auto">1. Made With Quality Ingredients<br>\n</h3>\n<p dir="auto">Each premix is made with high-quality ingredients that help produce soft texture and excellent taste. With this range of premixes, you can also create different flavours of cakes on your own! </p>\n<h3 dir="auto"><strong>2. The Best Prices For Cake Premix</strong></h3>\n<p>As commercial bakers, you need to deliver great taste while ensuring that the cost of cakes and bakes are optimal. We provide a range of cake premixes that can help you do just that. Moreover, you can bundle this with other ingredients, tools, equipment etc and reduce not just your premix but also your entire portfolio.</p>\n<h3 dir="auto">3. Quick &amp; Easy to Prepare</h3>\n<p dir="auto">All you need to do is add water, oil and bake - the premixes are made with the best ingredients so all you need to do is mix them with water and oil and bake to get a delicious cake sponge.</p>\n<h3 dir="auto">4. Cake Customization for Everyone</h3>\n<p dir="auto">We offer a wide variety of flavours you can add to the premixes, so there\'s something for everyone - whether you want vanilla or chocolate cakes, muffins or cupcakes. You can even add <a title="Fruit and Vegetable Powders" href="https://sourcegoodfood.com/collections/ingredients-collection-fruit-and-vegetable" target="_blank">fruit powders</a><span> </span>&amp;<span> </span><a title="Fruit Filling" href="https://sourcegoodfood.com/collections/fruit-fillings">fills<span> </span></a>to create unique taste experiences! and top of with<span> </span><a title="Cake Glaze" href="https://sourcegoodfood.com/collections/ingredients-glaze">glazes</a>.</p>',
    published_at: "2021-03-11T18:09:52+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Group-Cake premix",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/261639110852",
    image: {
      created_at: "2021-03-11T18:19:44+05:30",
      alt: null,
      width: 2973,
      height: 4460,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/extra-chocolate-cake.jpg?v=1615466984",
    },
  },
  {
    id: 277043871940,
    handle: "application-bakery",
    title: "Bakery",
    updated_at: "2022-11-22T13:12:18+05:30",
    body_html:
      '<h3 data-mce-fragment="1" data-pm-slice="1 1 []" dir="auto">Do you love Baking? Bake the best with bakery supplies ranging across ingredients, baking tools and equipment all in one place. </h3>\n<p>Bake with the fastest growing collection of bakery supplies for cakes, muffins, bread, cookies and many other applications. Baking is an art. Having the right baking tools and ingredients will help ensure that your baking endeavour is truly a work of art</p>\n<h3 data-mce-fragment="1" data-pm-slice="1 1 []" dir="auto">Great flavour, ingredient, baking tools and other bakery supplies</h3>\n<p dir="auto">Whether you want to bake a cake for your kid\'s birthday or start your own baking company, we have the ingredients, baking tools and equipment to help you hit the road running. <br></p>\n<p dir="auto">We understand the challenges that bakers face.  Whether it is creating the right recipe or finding the <strong>right ingredients and supplies</strong> at the right prices, we are here to help you accelerate your <strong>bakery business</strong></p>\n<p dir="auto">If you can\'t find a particular <strong>bakery solution</strong> or <strong>baking tools</strong> let us know and we\'ll help you find it.</p>',
    published_at: "2021-09-17T12:27:32+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Application-Bakery",
      },
      {
        column: "type",
        relation: "not_equals",
        condition: "Bakery Consultation",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/277043871940",
    image: {
      created_at: "2021-09-17T23:16:36+05:30",
      alt: "Bakery Supplies -  Baking  Ingredients, Tools and Equipment",
      width: 420,
      height: 630,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/pexels-los-muertos-crew-8478141.jpg?v=1633368592",
    },
  },
  {
    id: 267773837508,
    handle: "bakery-consultancy-services",
    title: "Bakery Consultancy Services",
    updated_at: "2022-11-08T10:51:32+05:30",
    body_html:
      "<p>Leverage several years of bakery research, development and production  experience to help you create exceptional products . Bakery consultancy services help you go from idea to product in the least amount of time.  Whether rectifying existing products that are already on store shelves or creating completely new products, consulting services can help you move from problem to solutions quickly. </p>",
    published_at: "2021-05-29T20:33:32+05:30",
    sort_order: "alpha-asc",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Consultancy Service-Bakery",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/267773837508",
  },
  {
    id: 278234333380,
    handle: "bakery-equipment-equipment-for-the-best-of-bakers",
    title: "Bakery Equipment- For the Best of Bakers",
    updated_at: "2022-11-08T10:51:34+05:30",
    body_html:
      '<h3 dir="auto" data-pm-slice="1 1 []">Bakery Equipment is our business</h3>\n<p dir="auto">We bring you the best<strong> bakery equipment</strong>, providing high-quality commercial baking equipment and commercial ovens to make your business successful.</p>\n<h3 dir="auto">We\'re making it easy to find what you need</h3>\n<p dir="auto">We make it easy for you to find what you need in a click — whether you\'re looking for one piece or a whole bakery\'s worth of <strong>equipment</strong>. We have several major brands of oven, mixers, and other equipment that you need. And if you have the need for some other machine, let us know and we\'ll be happy to find it for you. </p>\n<h3 dir="auto">What do we offer?</h3>\n<p dir="auto">We offer a wide range of bakery machinery and accessories, with different types of ovens, mixers, scales and more. You can also find great deals on commercial baking machines with bundles for sale!</p>',
    published_at: "2021-10-11T15:38:45+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Equipment-Bakery",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Tools-Baking Tools",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/278234333380",
    image: {
      created_at: "2021-10-11T16:20:16+05:30",
      alt: "Bakery equipment for the Best of Bakers",
      width: 5336,
      height: 3557,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/pexels-ron-lach-8880736.jpg?v=1633955616",
    },
  },
  {
    id: 275589988548,
    handle: "bakery-machinery",
    title: "Bakery Machinery - Machines for the Best of Bakers",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      '<h3 data-pm-slice="1 1 []" dir="auto">One Stop For Bakery Machinery</h3>\n<p data-pm-slice="1 1 []" dir="auto">Are you setting up a cloud bakery or restaurant or expanding your current baking factory ? We are your one-stop solution for all your commercial baking needs. No matter what your budget, we have the right mixers, ovens, and other bakery equipment to make your bakery dreams of setting up a bakery quickly come true.</p>\n<p><strong>Delight your bakery customer</strong></p>\n<p>Delight your customers with superior taste.  The right type of oven, mixers and other bakery equipment will ensure that your products are delivered consistently.  Uniform heat distribution, good mixing action helps deliver superior taste and quality </p>',
    published_at: "2021-08-30T09:34:13+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "machinery",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Bakery",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/275589988548",
    image: {
      created_at: "2021-08-30T09:48:44+05:30",
      alt: "Bakery Machinery - Bakery Machines for the Best of Bakers",
      width: 4460,
      height: 2973,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/person-puts-cookies-into-the-oven-to-bake.jpg?v=1633946353",
    },
  },
  {
    id: 272458481860,
    handle: "chocolates",
    title: "Baking and Industrial Chocolate",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      '<p><span data-mce-fragment="1">Chocolate is a food product made from roasted and ground cacao pods, that is available as a liquid, solid or paste, on its own or as a flavoring agent in other foods.</span></p>\n<ul>\n<li>Dark chocolate has chocolate liquor, cocoa butter, lecithin, sugar and vanilla.</li>\n<li>Milk chocolate has all of the above plus milk fats and milk solids.</li>\n<li>White chocolate contains everything milk chocolate does except chocolate liquor.</li>\n</ul>',
    published_at: "2021-07-26T10:58:44+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Chocolate",
      },
      {
        column: "title",
        relation: "contains",
        condition: "Chocolate",
      },
      {
        column: "title",
        relation: "not_contains",
        condition: "Premix",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/272458481860",
    image: {
      created_at: "2021-07-26T16:58:01+05:30",
      alt: null,
      width: 1536,
      height: 1920,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/coffee-1900194_1920.jpg?v=1627298882",
    },
  },
  {
    id: 272796942532,
    handle: "berry-collections",
    title: "Berry Collections",
    updated_at: "2022-10-12T14:51:13+05:30",
    body_html:
      "Consumers relish Berry flavours and tastes in various forms, from a strawberry milkshake to blueberry muffin. The burst of sweet and mildly tangy notes appeal to consumers world. Explore the range of Berry solutions for your next project .",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "title",
        relation: "contains",
        condition: "berry",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/272796942532",
  },
  {
    id: 262221103300,
    handle: "best-selling-products",
    title: "Best Selling Products & Services",
    updated_at: "2022-11-22T13:12:18+05:30",
    body_html:
      "Here are some of the most popular ingredient solutions and services for bakery, ice cream and confectionery applications. Time tested best sellers are extremely popular, try them and complete confidence.",
    published_at: "2021-03-19T07:53:17+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "title",
        relation: "contains",
        condition: "Best Selling",
      },
      {
        column: "title",
        relation: "not_contains",
        condition: "Best Selling",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/262221103300",
  },
  {
    id: 398368178395,
    handle: "beverage-consultancy-service",
    title: "Beverage Consultancy Service",
    updated_at: "2022-11-08T10:51:35+05:30",
    body_html:
      "Beverage (Juice, CSDs, Dairy Beverage) Consulting Services help you kick start your product development and go to market. With experts to help your formulate and fine tune your products, you will be able quickly launch new products and help consumers stay healthy and beat the weather in every season.",
    published_at: "2021-12-10T12:16:12+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Consultancy-Beverage",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/398368178395",
    image: {
      created_at: "2021-12-10T12:16:11+05:30",
      alt: "Beverage Consulting Services",
      width: 4460,
      height: 2973,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/tropical-poolside-cocktail.jpg?v=1639118771",
    },
  },
  {
    id: 265021817028,
    handle: "application-beverage-ingredients",
    title: "Beverage Ingredients",
    updated_at: "2022-11-08T10:51:32+05:30",
    body_html:
      "Beverage ingredients are core to beverages. Consumers turn to beverages to hydrate and quickly energise.  Today beverages are also a source of protein, vitamins and several other nutrients. Flavours, stabilisers and other ingredients play a vital role in delivering the right taste for the nutrition-conscious consumer. Beverages thus spans much beyond juices and CSDs, now encompasses everything sports nutrition drinks to dairy beverages",
    published_at: "2021-04-26T00:49:56+05:30",
    sort_order: "manual",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Beverages",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/265021817028",
    image: {
      created_at: "2021-09-14T16:34:37+05:30",
      alt: null,
      width: 925,
      height: 617,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/fresh-squeezed-orange-juice.jpg?v=1631617478",
    },
  },
  {
    id: 219769536678,
    handle: "application-health-beverage",
    title: "Beverages",
    updated_at: "2022-11-14T11:35:28+05:30",
    body_html:
      "<p>Our range of beverage ingredients and consulting services will help you meet the consumers need for on the go refreshment and nutrition. From stabilisers ,texturants , flavours, pulps and acidulants like citric acid to consulting and equipment we provide 360 degree beverage solutions. Whether you are making a juice or a dairy beverage we have the ingredients to help you get to market quickly and competetively</p>",
    published_at: "2020-09-17T15:24:28+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Application-Beverage",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/219769536678",
    image: {
      created_at: "2020-10-16T07:19:55+05:30",
      alt: "Health Beverage Drink",
      width: 2973,
      height: 4460,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/healthy-beet-juice.jpg?v=1602812995",
    },
  },
  {
    id: 271566241988,
    handle: "ingredients-cake-bakery-premix-concentrates",
    title: "Cake and Bakery Premix and Concentrates",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      '<h2 data-pm-slice="1 1 []" dir="auto">The one-stop destination for high-quality cake and other bakery premix and concentrates</h2>\n<h3 dir="auto">Why Use A Premix?</h3>\n<p>There are several reasons to use a premix, here are the top 4</p>\n<h3 dir="auto"></h3>\n<h3 dir="auto">1. Made With Quality Ingredients</h3>\n<p dir="auto">Each premix is made with high-quality ingredients that help produce soft texture and excellent taste. With this range of premixes, you can also create different flavours of cakes on your own! </p>\n<h3 dir="auto"><strong>2. Keep costs low</strong></h3>\n<p>As commercial bakers, you need to deliver great taste while ensuring that the cost of cakes and bakes are optimal. We provide a range of cake premixes that can help you do just that. Moreover, on sourcegoodfood.com you can bundle this with other ingredients, tools, equipment etc and reduce not just your premix but also your entire portfolio.</p>\n<h3 dir="auto">3. Quick &amp; Easy to Prepare</h3>\n<p dir="auto">All you need to do is add water, oil and bake - the premixes are made with the best ingredients so all you need to do is mix them with water and oil and bake to get a delicious cake sponge.</p>\n<h3 dir="auto">4. Cake Customization for Everyone</h3>\n<p dir="auto">We offer a wide variety of flavours you can add to<strong> the cake premixes and concentrates</strong>, so there\'s something for everyone - whether you want vanilla or chocolate cakes, muffins or cupcakes. You can even add <a href="https://sourcegoodfood.com/collections/ingredients-collection-fruit-and-vegetable" title="Fruit and Vegetable Powders" target="_blank">fruit powders</a> &amp; <a href="https://sourcegoodfood.com/collections/fruit-fillings" title="Fruit Filling">fills </a>to create unique taste experiences! and top of with <a href="https://sourcegoodfood.com/collections/ingredients-glaze" title="Cake Glaze">glazes</a>.</p>\n<h3 dir="auto"><strong></strong></h3>',
    published_at: "2021-07-15T13:45:55+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Premix",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Bakery Concentrate",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Bakery-Concentrate",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/271566241988",
    image: {
      created_at: "2021-07-18T10:33:45+05:30",
      alt: null,
      width: 925,
      height: 1388,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/cake-1971552_1920.jpg?v=1633330140",
    },
  },
  {
    id: 275827818692,
    handle: "world-coconut-day",
    title: "Celebrate World Coconut Day - Coconuts are more than just food",
    updated_at: "2022-11-08T10:51:34+05:30",
    body_html:
      '<p data-pm-slice="1 1 []" dir="auto">Celebrate World Coconut Day with us. We believe in good food for all, and the versatility of the coconut in all its forms. Use it in your baking, in your desserts, in your drinks, even in your sauces!</p>\n<p data-pm-slice="1 1 []" dir="auto">Coconut is a versatile food that can be used in many ways. From being used in ice cream to biscuits, to desserts, coconut can be made into so many different things. The flavour varies from the natural sweetness of the tender coconut ice creams to baked coconut cookies, from coconut burfi to coconut toffees. Avail additional 3% discount on coconut products with the discount code COCONUT3. This week only.</p>\n<h3 data-mce-fragment="1" dir="auto">What is World Coconut Day?</h3>\n<p data-mce-fragment="1" dir="auto">Every year on the second of September, all coconut growing countries across the globe observe this day as World Coconut Day. This day commemorates the foundation day of ICC an intergovernmental organization of coconut growing countries established under the aegis of the world trade organization in 1969. India is a founder member of ICC.</p>\n<h3 data-mce-fragment="1" dir="auto">Why should you celebrate?</h3>\n<p data-mce-fragment="1" dir="auto">Coconut is more than just a food - it\'s multi-faceted with amazing properties that make it versatile in cooking and can be used in numerous ways. Celebrating this day means acknowledging its importance in our lives and in all coconut growing countries across the world. This also allows us to celebrate our cultural heritage and enjoy its many benefits!</p>\n<h3 data-mce-fragment="1" dir="auto">The benefits of tender coconut</h3>\n<p data-mce-fragment="1" dir="auto">Green Coconut Pulp is sourced from young green coconuts harvested in the morning. The pulp is light, and not fibrous and sweet to taste. It can be enjoyed by itself or with other fruits. Tender coconut (green coconut) is loaded with the nutrition The water and tender pulp of green coconuts are packed with electrolytes and micronutrients.</p>',
    published_at: "2021-09-02T06:02:24+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "title",
        relation: "contains",
        condition: "Coconut",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/275827818692",
    image: {
      created_at: "2021-09-02T06:33:47+05:30",
      alt: "Collections Discover Coconut this World Coconut Day",
      width: 1280,
      height: 720,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/a-coconut-splits-open-and-spills-it-s-chocolate-chip-guts.jpg?v=1630576085",
    },
  },
  {
    id: 267247190212,
    handle: "ingredients-chocolate-and-cocoa-solutions",
    title: "Chocolate and Cocoa Solutions",
    updated_at: "2022-11-22T12:09:01+05:30",
    body_html: "",
    published_at: "2021-05-23T08:41:03+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Cocoa",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Chocolate Flavour",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Chocolate Bourbon Flavour",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Chocolate Flavour Encapsulated Powder",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "HAZELNUT CHOCOLATE FLAVOUR",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Milk Chocolate Flavour",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Swiss Chocolate Encapsulated",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Group-Chocolate Flavour",
      },
      {
        column: "title",
        relation: "contains",
        condition: "Dark Chocolate",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/267247190212",
  },
  {
    id: 236964610244,
    handle: "collection-aussee-oats",
    title: "Collection - Aussee Oats",
    updated_at: "2022-10-12T14:51:11+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Aussee-Oats",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236964610244",
  },
  {
    id: 278530392260,
    handle: "commercial-icecream-stabilisers",
    title: "Commercial Icecream Stabilisers",
    updated_at: "2022-11-08T10:51:35+05:30",
    body_html:
      '<p data-mce-fragment="1"><strong data-mce-fragment="1">Stabilisers</strong></p>\n<p data-mce-fragment="1">The main reasons for using stabilisers in ice cream are to</p>\n<ol data-mce-fragment="1">\n<li data-mce-fragment="1"> Improve texture by increasing the perception of creaminess, provide resistance to melting, and extend shelf life by retarding the growth of ice and lactose crystals during storage;</li>\n<li data-mce-fragment="1">Prevent the undesirable leaking of a clear watery serum layer during the melting of ice cream. This is called wheying off.</li>\n<li data-mce-fragment="1">To help prevent shrinkage.</li>\n</ol>',
    published_at: "2021-10-19T14:09:00+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Stabiliser",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/278530392260",
    image: {
      created_at: "2021-10-19T14:19:39+05:30",
      alt: null,
      width: 720,
      height: 480,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/ice-cream_stabiliser.jpg?v=1634633379",
    },
  },
  {
    id: 236557533380,
    handle: "collection-biocon-colors",
    title: "Company - Biocon Colors",
    updated_at: "2022-11-08T10:51:31+05:30",
    body_html: "",
    published_at: "2020-11-22T15:16:13+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Biocon-Colors",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236557533380",
  },
  {
    id: 222457299110,
    handle: "collection-bremil",
    title: "Company - Bremil",
    updated_at: "2022-10-12T14:51:10+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Bremil",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/222457299110",
  },
  {
    id: 236556189892,
    handle: "collection-danisco",
    title: "Company - Danisco (DuPont Food and Nutirtion)",
    updated_at: "2022-10-12T14:51:11+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Danisco",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236556189892",
  },
  {
    id: 236963594436,
    handle: "collection-giiava",
    title: "Company - Giiava",
    updated_at: "2022-10-12T14:51:11+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Giiava",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236963594436",
  },
  {
    id: 236556943556,
    handle: "collection-jb-cocoa",
    title: "Company - J B Cocoa",
    updated_at: "2022-10-12T14:51:11+05:30",
    body_html:
      '<div class="MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-direction-xs-column">\n<div class="MuiGrid-root MuiGrid-item">\n<div id="articleTextArea">\n<div class="MuiGrid-root MuiGrid-container">\n<div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-true">\n<div class="MuiGrid-root jss214 MuiGrid-container" id="outputText">\n<div class="MuiGrid-root jss213 MuiGrid-item MuiGrid-grid-xs-true">\n<p class="first-sentence-half"><br></p>\n<div></div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>',
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "JB-Coco",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236556943556",
  },
  {
    id: 236552454340,
    handle: "company-kerry",
    title: "Company - Kerry",
    updated_at: "2022-11-08T10:51:31+05:30",
    body_html:
      "Kerry is a leading manufacturer of food and beverage ingredients. It is well known for its dairy capabilities from popular dairy flavours like those of butter and milk to cheese powders etc. Kerry is a leading manufacturer of emulsifiers and enzyme solutions for categories like bakery, confectionery, ice creams etc.",
    published_at: "2020-11-22T12:45:06+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Kerry",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236552454340",
  },
  {
    id: 236552421572,
    handle: "collection-milk-specialties",
    title: "Company - Milk Specialties",
    updated_at: "2022-10-12T14:51:10+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Milk-Specialties",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236552421572",
  },
  {
    id: 219160608934,
    handle: "milne-microdried",
    title: "Company - Milne Microdried",
    updated_at: "2022-11-08T10:51:30+05:30",
    body_html:
      "<p> </p>\n<h1>Milne Microdried</h1>\n<p>Experience the goodness of Milne micro dried fruit powders. The real fruit minus the quality issues and challenges of handling fresh fruit and vegetable. Merely hydrate to get the great natural taste and nutrition. Perfect for fruit fillings, glazes , toppings and even as bits of fruit inside baked products like cakes and muffins, nutrition bars etc.</p>\n<p>It helps deliver the perfect fruit tastes in ice creams, yoghurts and other such products</p>",
    published_at: "2020-09-14T21:18:24+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Milne-MicroDried",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/219160608934",
  },
  {
    id: 236555632836,
    handle: "collection-polish-dairy",
    title: "Company - Polish Dairy",
    updated_at: "2022-10-12T14:51:11+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Polish-Dairy",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/236555632836",
  },
  {
    id: 219018789030,
    handle: "collection-volac",
    title: "Company - Volac",
    updated_at: "2022-10-12T14:51:09+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "title",
        relation: "contains",
        condition: "Volac",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/219018789030",
  },
  {
    id: 262349095108,
    handle: "consultancy-services",
    title: "Consultancy Services",
    updated_at: "2022-11-09T15:44:52+05:30",
    body_html:
      "Consultancy services are the only way to go to market quickly with a strong possibility of success. Leverage the  3 decades of professional experience and knowledge to help you go to market quickly. Consultancy services come in all shapes and sizes, from simpler recipe formulation to complex scale-up product runs and troubleshooting existing. SGF Consult, is the consultant service wing sourcegoodfood.com. SGF Consult partners with the best in the field to help you accelerate your new products to market.",
    published_at: "2021-08-06T14:01:40+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Consultancy-Service",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/262349095108",
    image: {
      created_at: "2021-07-25T21:24:22+05:30",
      alt: null,
      width: 925,
      height: 1388,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/meeting-flatlay.jpg?v=1627228462",
    },
  },
  {
    id: 271727886532,
    handle: "consumer-products",
    title: "Consumer Products",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      "<h1>Consumer Products</h1>\n<p><br>Ready to use consumer products for domestic as well as exports</p>",
    published_at: "2021-07-17T13:33:24+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "consumer-products",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/271727886532",
  },
  {
    id: 222570447014,
    handle: "county-milk-products",
    title: "County Milk Products",
    updated_at: "2022-10-12T14:51:10+05:30",
    body_html: "",
    published_at: null,
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "County-Milk-Products",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/222570447014",
    image: {
      created_at: "2020-09-29T22:50:51+05:30",
      alt: null,
      width: 244,
      height: 207,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/County_Milk_Products.jpg?v=1601400052",
    },
  },
  {
    id: 237080576196,
    handle: "collection-application-dairy",
    title: "Dairy Ingredients",
    updated_at: "2022-11-08T10:51:31+05:30",
    body_html:
      "Flavours, stabilisers and other dairy ingredients are critical to dairy products like cheese, butter, yoghurt and dairy drinks like milkshake, lassi, butter milk etc. From the right taste and texture to the right nutrition. The rick milky notes combined with exotic creamy tastes makes dairy products a platform for innovation.",
    published_at: "2020-11-29T08:09:06+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Application-Dairy",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/237080576196",
  },
  {
    id: 277964554436,
    handle: "direct-from-farm",
    title: "Direct from Farm",
    updated_at: "2022-11-08T10:51:34+05:30",
    body_html:
      "As consumers desire sustainability and traceability to get as close to the farm as possible, we've launched the direct from farm program. Get the best of farm and minimally processed food products at wholesale prices. We've partnered with a select group of supplier organisations, who ensure the best in class quality of the farm produce while helping ensure sustainability and improving the livelihoods of those who engage in such agriculture",
    published_at: "2021-10-01T22:13:33+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Control-Farm",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/277964554436",
  },
  {
    id: 278232236228,
    handle: "eggless-vanilla-cake-and-bakery-premix-powder",
    title: "Eggless Vanilla Cake and Bakery Premix (Powder)",
    updated_at: "2022-11-08T10:51:34+05:30",
    body_html:
      '<h3 data-mce-fragment="1" dir="auto" data-pm-slice="1 1 []">Why <span data-mce-fragment="1">Eggless Vanilla Cake Premix</span>\n</h3>\n<p data-mce-fragment="1" dir="auto" data-pm-slice="1 1 []">The<strong> Eggless Vanilla Cake Premix</strong> is a simple powder solution that will make your cake-making process easier, more consistent and less time-consuming. Forget the limits of eggs, forget the difficulty of sourcing the right ingredients, forget the hours you have to spend perfecting your technique</p>\n<h3 data-pm-slice="1 1 []" dir="auto">Quality is never compromised</h3>\n<p dir="auto">We are proud to provide products that ensure consistent sponge quality without compromising on taste or flavour. You can also ensure consistency in texture and colour as well as producing cakes that are as beautiful as they are delicious</p>\n<h3 data-pm-slice="1 1 []" dir="auto">Easy to use</h3>\n<p dir="auto">It\'s easy to make using this pre-mixed eggless vanilla cake mix. Just add water, oil, and sugar, then bake! It\'s that simple.</p>\n<p data-mce-fragment="1" dir="auto" data-pm-slice="1 1 []"> </p>\n<p data-mce-fragment="1" dir="auto" data-pm-slice="1 1 []"> </p>\n<p data-mce-fragment="1" dir="auto" data-pm-slice="1 1 []"> </p>',
    published_at: "2021-10-11T12:14:03+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "title",
        relation: "contains",
        condition: "Vanilla",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Premix",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/278232236228",
    image: {
      created_at: "2021-10-11T12:36:30+05:30",
      alt: "Eggless Vanilla Cake and Bakery Premix",
      width: 1280,
      height: 1920,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/pexels-polina-tankilevitch-4110001_1.jpg?v=1633936264",
    },
  },
  {
    id: 224111853734,
    handle: "ingredients-collection-emulsifiers",
    title: "Emulsifiers for cakes, bakes and confectionery",
    updated_at: "2022-11-08T10:51:31+05:30",
    body_html:
      "<p><strong>Emulsifiers</strong> are critical components of food that bind the fat and water parts together, ensuring the products stay as good till the end of shelf life. Monoglycerides, glycols, gums like xanthan, guar gum etc. and their combinations have proven to be excellent food emulsifiers and stabilisers.</p>\n<p>Emulsifiers help improve the taste and texture of bakery products, chocolates and help control melting and thickness (viscosity ) in products like ice creams, milkshakes etc.</p>",
    published_at: "2020-10-08T23:50:54+05:30",
    sort_order: "manual",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "type",
        relation: "equals",
        condition: "Emulsifier",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/224111853734",
  },
  {
    id: 267745263812,
    handle: "machinery",
    title: "Equipment & Machinery for Food Production",
    updated_at: "2022-11-08T10:51:32+05:30",
    body_html:
      "The right machinery ensures your product quality and consistency. They are as critical as the ingredients. In fact the type of machinery will often define the kind of ingredients and the formulations that will work on your production line.",
    published_at: "2021-05-29T12:29:01+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "machinery",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/267745263812",
  },
  {
    id: 263484866756,
    handle: "ingredients-nuts",
    title: "Exclusive Nuts Walnut, Almond for Ice creams and Bakes",
    updated_at: "2022-11-08T10:51:32+05:30",
    body_html:
      '<p data-mce-fragment="1" data-pm-slice="1 1 []" dir="auto"><strong>Why are Nuts like walnut, almond in ice cream so good</strong>?</p>\n<p data-mce-fragment="1" data-pm-slice="1 1 []" dir="auto">Well, it\'s usually because they\'re salty, crunchy and sweet.</p>\n<p data-mce-fragment="1" dir="auto">When you combine all these flavours together with the creaminess of the ice cream, it makes for a decadent dessert that is hard to beat. There are many brands that offer delicious variations of this flavour- most notably Ben &amp; Jerry\'s with their iconic "Chocolate Chip Cookie Dough" flavour.</p>\n<p data-mce-fragment="1" dir="auto">The most popular types of nuts in ice cream are walnuts, almonds and cashews.</p>\n<p data-mce-fragment="1" dir="auto">Walnuts are commonly used to make chocolate or vanilla-flavoured ice cream because their taste complements the sweet taste of ice cream. Almonds on the other hand go well with flavours like strawberry, pistachio because their rustic taste complements those flavours. whereas cashews just go well with chocolate, vanilla or butter pecan and almost every flavour. </p>',
    published_at: "2021-04-05T21:49:16+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Nuts",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/263484866756",
    image: {
      created_at: "2021-10-19T15:59:37+05:30",
      alt: "Exclusive Nuts like Walnuts an Almonds",
      width: 600,
      height: 400,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/walnut_almond_pista_cashew_macademia.jpg?v=1634639377",
    },
  },
  {
    id: 270714601668,
    handle: "ingredients-fruit-pulp",
    title: "Exotic Fruit Pulp for Ice creams, Bakery and Beverages",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      '<p><span><strong>Fruit pulp</strong> generally refers to the unconcentrated pulpy food product derived by means of an appropriate technological process, consisting majorly of total solids from the edible part of the fruit. Pulp is mushy in texture and may contain traces of fruits. It is the most basic product made from fresh fruit processing. It includes both the juice and the pulp, which is the stringy fibre that is frequently removed from the juice.</span></p>\n<p><span>Fruit pulps may be processed and kept longer without losing colour, flavour, or texture. </span></p>\n<p><span></span><span>Fruits pulps are generally used to manufacture ice creams, kulfi jams, cake fillings, milkshakes, marmalades, Gelato, fruit-flavoured yoghurt, jelly, fruit drinks, jams, lollipops, and even some speciality beer brewing </span></p>\n<p><span></span><span><strong>FROZEN FRESH FRUIT PULP</strong><br data-mce-fragment="1">Only the highest grade fruit is utilised in its preparation and is the Fruit is usually sorted by hand.<br data-mce-fragment="1">To avoid spoiling the batch, no damaged, rotting, or overripe fruit is processed.<br data-mce-fragment="1">After the fruit has been pulped, the pH may be adjusted using acid additions (citric, ascorbic).<br data-mce-fragment="1"><br data-mce-fragment="1">Brix can be changed to compensate for natural sweetness variations. This is done to match the fruit\'s natural brix level and keep the product consistent (other products in the market will have a nice flavour but will list water and sugar as primary ingredients).<br data-mce-fragment="1"><br data-mce-fragment="1"><br></span></p>',
    published_at: "2021-07-06T23:57:36+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Fruit Pulp",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/270714601668",
    image: {
      created_at: "2021-07-07T00:03:55+05:30",
      alt: "Fruit Plup for Ice cream, bakery and beverage",
      width: 2048,
      height: 1536,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/photo-1557616284-98bd90729b50.jpg?v=1634636773",
    },
  },
  {
    id: 270882242756,
    handle: "exports",
    title: "Exports",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html: "Peanut Butter Export Range.",
    published_at: "2021-07-08T20:00:59+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "exports",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/270882242756",
    image: {
      created_at: "2021-07-08T20:00:58+05:30",
      alt: null,
      width: 1880,
      height: 1253,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/exports.jpg?v=1625754658",
    },
  },
  {
    id: 276459454660,
    handle: "wholesale-gourmet",
    title: "F & B Packaged Food Wholesale",
    updated_at: "2022-11-08T10:51:34+05:30",
    body_html:
      "Are you a food and beverage retailer, Are you planning to stock up for a party or exotic home cooking? Get the best in class packaged foods to keep your customers and guests coming back for more, at wholesale prices.",
    published_at: "2021-09-09T14:53:56+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Control-Wholesale",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/276459454660",
    image: {
      created_at: "2021-09-09T15:01:47+05:30",
      alt: "wholesale gourmet",
      width: 2640,
      height: 3960,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/pexels-ponyo-sakana-4194622.jpg?v=1631179908",
    },
  },
  {
    id: 223696421030,
    handle: "ingredients-flavour",
    title: "Flavour Essence Solutions",
    updated_at: "2022-11-14T11:35:28+05:30",
    body_html:
      "<h3><strong>Flavour Essence Solutions </strong></h3>\n<p><strong>They are critical </strong> to ensure consistent taste from one batch to the next. But every essence in the same. Some work well when cooked or baked a fresh, but gives away soon after. Some degrade in the presence of acids and other chemicals, heat etc. </p>\n<p>Our select collection of flavour essences that can help your Food and Beverage products stand out vs the competition. We have carefully curated the flavour essence so that you can choose the flavour essence that is the most appropriate with application. Whether, bakery like cakes, muffins breads etc, confectionery or juices and other beverages, these flavour essence will maximize your products quality and  reinvigorate your brand promise, while helping you deliver superior consumer experiences</p>\n<p><strong>Flavour Essence Solutions and Flavour Emulsions go hand in hand. To know more get in touch with us</strong></p>",
    published_at: "2020-10-05T22:05:48+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Flavour-Essence",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Flavour-Essence-Emulsion",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/223696421030",
    image: {
      created_at: "2020-10-17T11:19:13+05:30",
      alt: "Flavour Ingredients",
      width: 4460,
      height: 2973,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/blueberries-in-hand.jpg?v=1602913754",
    },
  },
  {
    id: 270628192452,
    handle: "flavour-of-the-month",
    title: "Flavour of March - Mango",
    updated_at: "2022-11-08T10:51:32+05:30",
    body_html:
      "<h3>Try our flavour of the Month - Mango, and get up to 5% discount</h3>\n<p>Every month we'll feature a flavour, where we'll go deep and help you understand how you can leverage these flavours to create fantastic new products and tastes in particular applications, </p>\n<p>The flavour for the Month March is Mango. A summer special. Mango is very popular in juices, milk shakes, lassi, ice cream and even teas. Mango Icing is popular in bakery and mango cream biscuits are well accepted. Mango is a favourite confectionery, especially sugar candy.<br></p>",
    published_at: "2021-07-06T08:28:41+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Mango",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Raw-Mango",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Green-Mango",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/270628192452",
  },
  {
    id: 406338404571,
    handle: "flavours-of-summer",
    title: "Flavours of Summer",
    updated_at: "2022-11-08T10:51:35+05:30",
    body_html:
      '<div data-mce-fragment="1">Summer is officially here! </div>\n<div data-mce-fragment="1">As temperatures soar, the demand for cooling beverages and food items skyrocket to beat the heat. To capture this demand,<span data-mce-fragment="1"> </span><a href="http://www.sourcegoodfood.com/" data-saferedirecturl="https://www.google.com/url?q=http://www.sourcegoodfood.com&amp;source=gmail&amp;ust=1647476233905000&amp;usg=AOvVaw2-9_Fm_8mXyMkKaTFaxNFn" data-mce-fragment="1" data-mce-href="http://www.sourcegoodfood.com/" target="_blank">www.sourcegoodfood.com</a><span data-mce-fragment="1"> </span>brings you a variety of summer flavours that have a wide range of applications in all kinds of cooling desserts and beverages. </div>\n<div data-mce-fragment="1">While seasonal flavours like mango, watermelon, strawberry and mint are all-time favourites; we implore you to try out some unique flavours like chilli as a way of switching things up and bringing unconventional options to keep your consumers on their toes.</div>\n<div data-mce-fragment="1">Keep checking this space for more information and offers.</div>',
    published_at: "2022-03-16T06:05:02+05:30",
    sort_order: "created",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Mango",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Watermelon",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Mint",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Lemon",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Spearmint",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Red-Chili",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Green-Chilli",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Cucumber",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Rose",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Profile-Roselle",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/406338404571",
    image: {
      created_at: "2022-03-16T06:15:08+05:30",
      alt: "Flavours of Summer - Juice and Ice cream flavour",
      width: 1280,
      height: 838,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/pexels-lisa-fotios-109275.jpg?v=1647391508",
    },
  },
  {
    id: 223067734182,
    handle: "ingredients-flavours-essence-extracts-cocoa",
    title: "Flavours, Essence, Extracts and Cocoa",
    updated_at: "2022-11-14T11:35:28+05:30",
    body_html:
      "<p><strong>Flavours (Essence), natural extracts and cocoa powder,</strong> vanilla powder etc are critical to taste. Whether you are baking a cake or making ice cream, flavours, cocoa powder and extracts elevate the taste. Chocolate flavours, sweet vanillas, or rich buttery notes, are all rooted in flavours, natural extracts and cocoa</p>\n<h3>Find the Flavours, Essence, Extracts and Cocoa that you need</h3>",
    published_at: "2020-10-02T06:43:55+05:30",
    sort_order: "manual",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Extracts",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Flavour-Essence",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Cocoa",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Flavour-Essence",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/223067734182",
    image: {
      created_at: "2020-10-02T06:43:54+05:30",
      alt: "Flavours, Essence, Extracts and Cocoa",
      width: 4460,
      height: 2973,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/freshly-picked-coffee-beans.jpg?v=1638876310",
    },
  },
  {
    id: 402489180379,
    handle: "food-and-beverage-technical-consultancy",
    title: "Food and Beverage Technical Consultancy",
    updated_at: "2022-11-09T15:44:52+05:30",
    body_html:
      "<p>Food and Beverage Technical Consultancy helps you get your markets off the idea board and into production lines and eventually into the market quickly. Leveraging over 100 years of combined technical expertise the consultants who have partnered with us are well recognized in the food and beverage production industry. They have had 1000s of hours of experience in resolving industry and production challenges both as in house technical experts as well as independent consultants.</p>\n<p>As food technology experts who understand both the nuances of the product as well as commercial line production, their help has helped several clients resolve challenges quickly. With a wide range of expertise and experience, leverage their expertise in getting your products to market quickly. </p>\n<p>Get in touch with them today.  Every consultant offers a free first meeting before getting into a formal engagement. Book Your Slot Now</p>",
    published_at: "2022-02-03T10:56:34+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Consultancy-Service",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/402489180379",
    image: {
      created_at: "2022-02-03T12:18:17+05:30",
      alt: "Food and Beverage Technical Consultancy - Food Technology Consulting",
      width: 905,
      height: 744,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/fun-team-work.jpg?v=1643870898",
    },
  },
  {
    id: 275786563780,
    handle: "food-products",
    title: "Food products",
    updated_at: "2022-11-08T10:51:34+05:30",
    body_html:
      '<h1><span data-mce-fragment="1">Food products</span></h1>\n<p><span data-mce-fragment="1">Food additives are substances added to food to preserve flavor or enhance taste, appearance, or other sensory qualities. Some additives have been used for centuries as part of an effort to preserve food, for example vinegar, salt, smoke, sugar, etc. This allows for longer-lasting foods such as bacon, sweets or wines.</span></p>\n<p><span data-mce-fragment="1">Rice, beans, puree paste, sauce and noodles</span></p>',
    published_at: "2021-09-01T18:08:47+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "food products",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/275786563780",
    image: {
      created_at: "2021-09-03T11:54:40+05:30",
      alt: null,
      width: 1920,
      height: 1282,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/meal-5921491_1920.jpg?v=1630650280",
    },
  },
  {
    id: 278546612420,
    handle: "food-texturant-stabiliser-and-hydrocolloids",
    title: "Food Texturant, stabiliser and hydrocolloids",
    updated_at: "2022-11-08T10:51:35+05:30",
    body_html:
      '<p><strong>Food Texturant as Thickener</strong></p>\n<p>In the liquid state food, thickeners are used to improve the viscosity. Dairy products, puddings, dessert fillings, soups, sauces, dressings, and bread mixes all employ thickeners.<br data-mce-fragment="1"></p>\n<p><strong>Food Texturant as Emulsifier</strong><br data-mce-fragment="1">Emulsifiers are used in foods to keep the oil from separating from the aqueous phase. They\'re also utilised to make solid powders containing embedded micro-encapsulated oils when combined with other encapsulation components. Emulsifiers are used to stabilise flavour oils in beverage emulsions and to encapsulate flavour and other volatile chemicals into powders in food flavour systems.</p>',
    published_at: "2021-10-20T00:18:29+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: true,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Emulsifier",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Starch and hydrocolloid",
      },
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Stabiliser",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/278546612420",
  },
  {
    id: 272403792068,
    handle: "fruit-fillings",
    title: "Fruit Fillings",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html: "",
    published_at: "2021-07-25T15:59:35+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "type",
        relation: "equals",
        condition: "Fruit Filling",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/272403792068",
  },
  {
    id: 271767568580,
    handle: "ingredients-glaze",
    title: "Glazes",
    updated_at: "2022-11-08T10:51:33+05:30",
    body_html:
      "The variety of glazes allow for more options and opportunity for dessert makers to create a well balanced dessert coatings. provides the consumers with glossy and bright finish to the product, it can also come in fruit flavors to all the fruit lovers.",
    published_at: "2021-07-18T10:26:37+05:30",
    sort_order: "best-selling",
    template_suffix: "",
    disjunctive: false,
    rules: [
      {
        column: "tag",
        relation: "equals",
        condition: "Collection-Glaze",
      },
    ],
    published_scope: "global",
    admin_graphql_api_id: "gid://shopify/Collection/271767568580",
    image: {
      created_at: "2021-07-18T10:41:18+05:30",
      alt: null,
      width: 540,
      height: 539,
      src: "https://cdn.shopify.com/s/files/1/0439/4287/1206/collections/glazed_cake.jpg?v=1626585078",
    },
  },
];

export default fifity_smart_collections;
